version: '3'
services:
  database:
    image: mysql:8
    restart: always
    container_name: imoveis-mysql
    environment:
      MYSQL_DATABASE: 'imoveis'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    volumes:
      - imoveis-mysql:/var/lib/mysql

volumes:
  imoveis-mysql: